from pathlib import Path
from typing import Any

def get_alembic_head_revision() -> str | None: ...
def suggest_image_tag_from_meta(meta: dict[str, Any] | None) -> str | None: ...
def read_backup_meta(backup_zip_path: str | Path) -> dict[str, Any] | None: ...
def check_db_integrity(db_path: str | Path) -> bool: ...
def snapshot_sqlite(db_path: str | Path, out_path: str | Path) -> bool: ...
