---
codecov:
  token: 13987d18-8800-42bc-a9e0-89dbfa9f2e9c
  require_ci_to_pass: false

coverage:
  precision: 2
  round: down
  range: "0..100"
  status:
    project:
      default:
        # Show current coverage but don't fail PRs while we're stabilizing tests
        target: auto
        threshold: 0.5%
    patch:
      default:
        # Allow small volatility on new/changed code without blocking
        target: auto
        threshold: 1%

ignore:
  - "tests/**"
  - "unit_tests/**"
  - "researcharr/tests/**"
  - "docs/**"
  - "site/**"
  - ".venv/**"
  - "venv/**"
  - ".venv*/**"
  - "scripts/**"
  - "backups-scratch/**"
  - "container_build/**"
  - "repo-mirror.git/**"
  - "researcharr.egg-info/**"
  - "home/**"
  - "htmlcov/**"
  - "node_modules/**"
  - "alembic/versions/**"
  - "typings/**"
  - ".tmp/**"
  - "**/*.pyi"
  - "**/conftest.py"
  - "**/__pycache__/**"
  - "**/test_utils/**"
  - "static/**"
  - "templates/**"

  # Bisect/replay artifacts produced during flaky-test triage
  - "**/replay_*.xml"
  - "**/replay_*.log"
  - "**/pairwise_bisect_*.xml"
  - "**/random_*.xml"
  - "**/researcharr-bisect/**"
