import logging
from typing import Any, Optional

LOG_PATH: str
SCRIPT: str
CONFIG_PATH: Optional[str]

def run_job(*args: Any, **kwargs: Any) -> Any: ...
def main(once: bool = False) -> None: ...
def load_config(path: Optional[str] = ...) -> Optional[dict]: ...
def execute_job() -> Any: ...
def signal_handler(signum: int, frame: Any) -> Any: ...
def start_background_thread() -> Any: ...
def update_metrics() -> None: ...
def setup_logger(
    name: str = ..., log_file: str = ..., level: Optional[int] = ...
) -> logging.Logger: ...
def setup_scheduler() -> Any: ...
