from typing import Any, Optional, Mapping
import logging

# Basic package-level exports used across the tests
DB_PATH: str

# The package exposes a nested implementation module as the attribute
# `researcharr` (set at runtime by the package shim). Declare it so
# Pylance can resolve expressions like `researcharr.researcharr.init_db`.
researcharr: Any

def init_db(path: Optional[str] = ...) -> None: ...

def setup_logger(name: str = ..., log_file: str = ..., level: Optional[int] = ...) -> logging.Logger: ...

def load_config(path: Optional[str] = ...) -> Mapping[str, Any]: ...

def check_radarr_connection(url: str, api_key: str, logger: logging.Logger) -> bool: ...

def check_sonarr_connection(url: str, api_key: str, logger: logging.Logger) -> bool: ...

def has_valid_url_and_key(instances: Any) -> bool: ...

def create_metrics_app() -> Any: ...

def serve() -> None: ...

def get_user_by_username(username: str) -> Any: ...

def create_user(username: str, password_hash: str) -> None: ...

__version__: str
