from pathlib import Path

def create_backup_file(
    config_root: str | Path,
    backups_dir: str | Path,
    prefix: str = "",
) -> str | None: ...
def prune_backups(
    backups_dir: str | Path,
    cfg: dict | None = None,
) -> None: ...
def get_backup_info(path: str | Path) -> dict | None: ...
def list_backups(
    backups_dir: str | Path, *, pattern: str | None = None
) -> list[dict[str, object]]: ...
def restore_backup(path: str | Path, dest: str | Path) -> bool: ...
def validate_backup_file(path: str | Path) -> bool: ...
def get_backup_size(path: str | Path) -> int: ...
def cleanup_temp_files(tmp_dir: str | Path) -> None: ...
def get_default_backup_config() -> dict: ...
def merge_backup_configs(default: dict, user: dict) -> dict: ...
