from typing import Any

from flask import Flask

def create_app() -> Flask: ...
def load_user_config() -> dict[str, Any]: ...
def save_user_config(cfg: dict[str, Any], path: str | None = ...) -> None: ...
def get_user_by_username(username: str) -> dict[str, Any] | None: ...
