from typing import Any, Dict, Optional

from flask import Flask

def create_app() -> Flask: ...
def load_user_config() -> Dict[str, Any]: ...
def save_user_config(cfg: Dict[str, Any], path: Optional[str] = ...) -> None: ...
def get_user_by_username(username: str) -> Optional[Dict[str, Any]]: ...
