import logging
from typing import Any

DB_PATH: str

def init_db(db_path: str | None = ...) -> None: ...
def setup_logger(
    name: str = ..., log_file: str = ..., level: int | None = ...
) -> logging.Logger: ...
def has_valid_url_and_key(instances: Any) -> bool: ...
def check_radarr_connection(*args: Any, **kwargs: Any) -> bool: ...
def check_sonarr_connection(*args: Any, **kwargs: Any) -> bool: ...
def load_config(path: str = ...) -> dict[str, Any]: ...
def create_metrics_app() -> Any: ...
def serve() -> None: ...
