from typing import Any, Optional

def run_job() -> None: ...
def main(once: bool = False) -> None: ...

def setup_scheduler() -> Any: ...

def setup_logger(name: Optional[str] = ..., level: Optional[int] = ...) -> Any: ...
