from typing import Any

def run_job() -> None: ...
def main(once: bool = False) -> None: ...
def setup_scheduler() -> Any: ...
def setup_logger(name: str | None = ..., level: int | None = ...) -> Any: ...
