"""initial_schema_baseline

Revision ID: bfefe5dda66b
Revises:
Create Date: 2025-11-09 20:48:01.366131

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bfefe5dda66b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "global_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("items_per_cycle", sa.Integer(), nullable=False),
        sa.Column("cycle_interval_minutes", sa.Integer(), nullable=False),
        sa.Column("state_management_period_days", sa.Integer(), nullable=False),
        sa.Column(
            "sort_strategy",
            sa.Enum(
                "CUSTOM_FORMAT_SCORE_ASC",
                "CUSTOM_FORMAT_SCORE_DESC",
                "ALPHABETICAL_ASC",
                "ALPHABETICAL_DESC",
                "EXTERNAL_ID_ASC",
                "EXTERNAL_ID_DESC",
                "RANDOM",
                name="sortstrategy",
            ),
            nullable=False,
        ),
        sa.Column("retry_failed_items", sa.Boolean(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("retry_delay_minutes", sa.Integer(), nullable=False),
        sa.Column("notifications_enabled", sa.Boolean(), nullable=False),
        sa.Column("notify_on_search_started", sa.Boolean(), nullable=False),
        sa.Column("notify_on_search_completed", sa.Boolean(), nullable=False),
        sa.Column("notify_on_cycle_completed", sa.Boolean(), nullable=False),
        sa.Column("notify_on_errors", sa.Boolean(), nullable=False),
        sa.Column("notify_daily_summary", sa.Boolean(), nullable=False),
        sa.Column("daily_summary_time", sa.String(length=5), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "managed_apps",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("app_type", sa.Enum("RADARR", "SONARR", name="apptype"), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("base_url", sa.String(length=255), nullable=False),
        sa.Column("api_key", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("use_custom_settings", sa.Boolean(), nullable=False),
        sa.Column("custom_items_per_cycle", sa.Integer(), nullable=True),
        sa.Column("custom_cycle_interval_minutes", sa.Integer(), nullable=True),
        sa.Column("custom_state_management_period_days", sa.Integer(), nullable=True),
        sa.Column(
            "custom_sort_strategy",
            sa.Enum(
                "CUSTOM_FORMAT_SCORE_ASC",
                "CUSTOM_FORMAT_SCORE_DESC",
                "ALPHABETICAL_ASC",
                "ALPHABETICAL_DESC",
                "EXTERNAL_ID_ASC",
                "EXTERNAL_ID_DESC",
                "RANDOM",
                name="sortstrategy",
            ),
            nullable=True,
        ),
        sa.Column("custom_retry_failed_items", sa.Boolean(), nullable=True),
        sa.Column("custom_max_retries", sa.Integer(), nullable=True),
        sa.Column("custom_retry_delay_minutes", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("last_sync_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("app_type", "base_url", name="_app_type_url_uc"),
    )
    op.create_table(
        "search_cycles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("app_id", sa.Integer(), nullable=False),
        sa.Column("cycle_number", sa.Integer(), nullable=False),
        sa.Column(
            "phase",
            sa.Enum("SYNCING", "SEARCHING", "COOLDOWN", "RESETTING", name="cyclephase"),
            nullable=False,
        ),
        sa.Column("total_items", sa.Integer(), nullable=False),
        sa.Column("items_searched", sa.Integer(), nullable=False),
        sa.Column("items_succeeded", sa.Integer(), nullable=False),
        sa.Column("items_failed", sa.Integer(), nullable=False),
        sa.Column("items_in_retry_queue", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("next_cycle_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["app_id"], ["managed_apps.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("app_id", "cycle_number", name="_app_cycle_number_uc"),
    )
    op.create_table(
        "tracked_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("app_id", sa.Integer(), nullable=False),
        sa.Column("arr_id", sa.Integer(), nullable=False),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("tvdb_id", sa.Integer(), nullable=True),
        sa.Column("imdb_id", sa.String(length=20), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("monitored", sa.Boolean(), nullable=False),
        sa.Column("has_file", sa.Boolean(), nullable=False),
        sa.Column("custom_format_score", sa.Float(), nullable=False),
        sa.Column("search_count", sa.Integer(), nullable=False),
        sa.Column("last_search_at", sa.DateTime(), nullable=True),
        sa.Column("failed_search_count", sa.Integer(), nullable=False),
        sa.Column("next_retry_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["app_id"], ["managed_apps.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("app_id", "arr_id", name="_app_arr_id_uc"),
    )
    op.create_table(
        "processing_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("app_id", sa.Integer(), nullable=False),
        sa.Column("tracked_item_id", sa.Integer(), nullable=True),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["app_id"], ["managed_apps.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tracked_item_id"], ["tracked_items.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("processing_logs")
    op.drop_table("tracked_items")
    op.drop_table("search_cycles")
    op.drop_table("managed_apps")
    op.drop_table("global_settings")
    # ### end Alembic commands ###
