from typing import Any

class PluginRegistry:
    def __init__(self) -> None: ...
    def register(self, name: str, cls: Any) -> None: ...
    def get(self, name: str) -> Any: ...
    def discover_local(self, plugins_dir: str) -> None: ...
    def create_instance(self, plugin_name: str, config: dict) -> Any: ...
    def list_plugins(self) -> list[str]: ...

__all__ = ["PluginRegistry"]
