name: Alpine CI (build, test, trivy, publish)

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ main, development ]
    tags: [ 'v*', '*' ]
  pull_request:
    branches: [ main, development ]

jobs:
  alpine-ci:
    name: Build Alpine image, run tests, Trivy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up QEMU and buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Alpine image (loaded locally)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.alpine
        push: false
        load: true
        tags: local/researcharr:alpine

    - name: Run mypy + pytest inside built Alpine image
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        docker run --rm --entrypoint "" -v "${{ github.workspace }}":/app -w /app -e PYTHONPATH=/app local/researcharr:alpine sh -lc "python -m pip install --upgrade pip && pip install mypy && mypy . && pytest tests/ --maxfail=1 -q"

    - name: Run Trivy scan
      run: |
        docker run --rm -v "${{ github.workspace }}":/workspace -w /workspace aquasec/trivy:latest image --format json -o build/artifacts/trivy-report-alpine.json local/researcharr:alpine || true

    - name: Upload Trivy JSON artifact
      uses: actions/upload-artifact@v4
      with:
        name: trivy-report-alpine
        path: build/artifacts/trivy-report-alpine.json

    - name: Prepare minimal config for smoke-test
      run: |
        mkdir -p build/smoke-config
        cp config.example.yml build/smoke-config/config.yml || true

    - name: Run Alpine smoke-test (health endpoint + basic acceptance)
      id: smoke_test
      continue-on-error: true
      run: |
        set -euo pipefail
        CONTAINER_NAME=smoke_test_instance
        mkdir -p build/smoke-logs
        docker run --rm -d --name ${CONTAINER_NAME} -v "${{ github.workspace }}/build/smoke-config":/config -e CONFIG_PATH=/config/config.yml -p 2929:2929 local/researcharr:alpine || true
        HEALTH_OK=0
        for i in $(seq 1 60); do
          OUTPUT=$(curl -sS -f http://127.0.0.1:2929/health 2>/dev/null || true)
          if [ -n "$OUTPUT" ]; then
            if echo "$OUTPUT" | jq -e '.status and .config and .db' >/dev/null 2>&1; then
              echo "smoke-test: health ok and JSON shape validated"
              HEALTH_OK=1
              break
            else
              echo "smoke-test: health returned but JSON missing expected keys; output=$OUTPUT"
            fi
          fi
          sleep 1
        done
        if [ "$HEALTH_OK" -ne 1 ]; then
          echo "smoke-test: failed to validate health endpoint"
          docker logs ${CONTAINER_NAME} > build/smoke-logs/${CONTAINER_NAME}.log 2>&1 || true
          tar -czf build/smoke-logs.tar.gz -C build smoke-logs || true
          docker stop ${CONTAINER_NAME} || true
          exit 1
        fi
        docker stop ${CONTAINER_NAME} || true

    - name: Upload smoke-test logs (alpine)
      if: steps.smoke_test.outcome == 'failure'
      uses: actions/upload-artifact@v4
      with:
        name: smoke-logs-alpine
        path: build/smoke-logs.tar.gz

    - name: Compute VERSION
      id: version
      run: |
        if [[ "${GITHUB_REF}" =~ refs/tags/(.*) ]]; then
          echo "VERSION=${BASH_REMATCH[1]}" >> $GITHUB_ENV
        else
          echo "VERSION=0.0.0-alpha.${GITHUB_RUN_ID}" >> $GITHUB_ENV
        fi

    - name: Log in to GitHub Container Registry
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development' || startsWith(github.ref, 'refs/tags/')
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag and push alpine image to GHCR (main/development/tags only)
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development' || startsWith(github.ref, 'refs/tags/')
      run: |
        docker tag local/researcharr:alpine ghcr.io/${{ github.repository }}:${{ env.VERSION }}-alpine
        docker tag local/researcharr:alpine ghcr.io/${{ github.repository }}:alpine
        docker push ghcr.io/${{ github.repository }}:${{ env.VERSION }}-alpine
        docker push ghcr.io/${{ github.repository }}:alpine

    - name: Publish dev tag (development branch only)
      if: github.ref == 'refs/heads/development'
      run: |
        docker tag local/researcharr:alpine ghcr.io/${{ github.repository }}:dev-${{ github.run_id }}
        docker push ghcr.io/${{ github.repository }}:dev-${{ github.run_id }}
