name: Alpine CI (build, test, trivy, publish)

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ main, development ]
    tags: [ 'v*', '*' ]
  pull_request:
    branches: [ main, development ]

jobs:
  alpine-ci:
    name: Build Alpine image, run tests, Trivy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up QEMU and buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Alpine image (loaded locally)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.alpine
        push: false
        load: true
        tags: local/researcharr:alpine

    - name: Run mypy + pytest inside built Alpine image
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        docker run --rm --entrypoint "" -v "${{ github.workspace }}":/app -w /app -e PYTHONPATH=/app local/researcharr:alpine sh -lc "python -m pip install --upgrade pip && pip install mypy && mypy . && pytest tests/ --maxfail=1 -q"

    - name: Run Trivy scan
      run: |
        docker run --rm -v "${{ github.workspace }}":/workspace -w /workspace aquasec/trivy:latest image --format json -o build/artifacts/trivy-report-alpine.json local/researcharr:alpine || true

    - name: Upload Trivy JSON artifact
      uses: actions/upload-artifact@v4
      with:
        name: trivy-report-alpine
        path: build/artifacts/trivy-report-alpine.json

    - name: Compute VERSION
      id: version
      run: |
        if [[ "${GITHUB_REF}" =~ refs/tags/(.*) ]]; then
          echo "VERSION=${BASH_REMATCH[1]}" >> $GITHUB_ENV
        else
          echo "VERSION=0.0.0-alpha.${GITHUB_RUN_ID}" >> $GITHUB_ENV
        fi

    - name: Log in to GitHub Container Registry
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development' || startsWith(github.ref, 'refs/tags/')
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Alpine image to GHCR (main/development/tags only)
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development' || startsWith(github.ref, 'refs/tags/')
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.alpine
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:${{ env.VERSION }}-alpine
          ghcr.io/${{ github.repository }}:alpine
