name: Docker Publish

# Trigger when the CI workflow completes successfully
on:
  workflow_run:
    workflows: [ "CI" ]
    types:
    - completed

jobs:
  docker:
    # Only run when the upstream CI workflow finished successfully and the event was a push.
    # This allows publishing branch-tagged images for any branch after CI passes.
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' }}
    runs-on: ubuntu-latest
    concurrency:
      group: docker-publish-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract branch name from workflow_run
      id: extract_branch
      run: echo "branch=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_OUTPUT
    - name: Set lowercase repository name
      id: repo_name
      run: echo "REPO_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
    - name: Build and push Docker image (all branches)
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ env.REPO_NAME }}:${{ steps.extract_branch.outputs.branch }}
          ghcr.io/${{ env.REPO_NAME }}:branch-${{ steps.extract_branch.outputs.branch }}
        cache-from: type=gha,scope=researcharr-build-cache
        cache-to: type=gha,mode=max,scope=researcharr-build-cache
        build-args: |
          PYTHON_VERSION=3.13
    - name: Additional tags for main/development
      if: ${{ steps.extract_branch.outputs.branch == 'main' || steps.extract_branch.outputs.branch == 'development' }}
      run: |
        REPO=ghcr.io/${{ env.REPO_NAME }}
        BRANCH=${{ steps.extract_branch.outputs.branch }}
        if [ "$BRANCH" = "main" ]; then docker tag $REPO:main $REPO:latest && docker push $REPO:latest; fi
        if [ "$BRANCH" = "development" ]; then docker tag $REPO:development $REPO:development && docker push $REPO:development; fi
