name: CI

on:

  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.11, 3.12, 3.13 ]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black isort flake8 mypy pytest pytest-cov
    - name: Lint with flake8
      run: |
        flake8 . --count --show-source --statistics
    - name: Check formatting with black
      run: |
        black --check .
    - name: Check import order with isort
      run: |
        isort --check-only .
    - name: Type check with mypy
      run: |
        mypy .
    - name: Run tests with pytest
      run: |
        pytest tests/ --maxfail=3 --disable-warnings -v --cov=researcharr
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
      continue-on-error: true

  docker:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v4
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract branch name
      id: extract_branch
      run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
    - name: Set lowercase repository name
      id: repo_name
      run: echo "REPO_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
    - name: Build and push Docker image (main)
      if: github.ref == 'refs/heads/main'
      run: |
        docker build -t ghcr.io/${{ env.REPO_NAME }}:latest .
        docker push ghcr.io/${{ env.REPO_NAME }}:latest
    - name: Build and push Docker image (development)
      if: github.ref == 'refs/heads/development'
      run: |
        docker build -t ghcr.io/${{ env.REPO_NAME }}:development .
        docker push ghcr.io/${{ env.REPO_NAME }}:development
