name: Docs link check

on:
  pull_request:
    branches:
    - development
    - main

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Ruby (for html-proofer)
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
    - name: Install html-proofer
      run: |
        gem install html-proofer
    - name: Build site (no-op for raw markdown)
      run: |
        # If you have a static site generator, run it here. For plain markdown we just check docs/ files
        mkdir -p site
        cp -a docs/. site/
    - name: Run html-proofer link check
      run: |
        htmlproofer site --check-external-hash=false --allow-hash-href
