name: Deploy docs previews to GitHub Pages

on:
  push:
    # run on all branches except main
    branches-ignore: [ main ]

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install docs deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then
            pip install -r requirements-dev.txt
          else
            pip install mkdocs mkdocs-material
          fi

      - name: Build MkDocs site
        run: |
          rm -rf site_build
          if command -v mkdocs >/dev/null 2>&1; then
            mkdocs build -d site_build
          fi

      - name: Prepare preview site directory and copy built docs
        env:
          PREVIEW_BRANCH: ${{ github.ref_name }}
        run: |
          set -euo pipefail
          rm -rf site
          mkdir -p site/previews
          # If a built MkDocs site exists, publish the built HTML. Otherwise fall back to raw docs.
          if [ -d site_build ]; then
            cp -a site_build/. site/previews/${PREVIEW_BRANCH}
          else
            cp -a docs/. site/previews/${PREVIEW_BRANCH}
          fi

      - name: Deploy previews to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
