"""Alembic environment configuration for researcharr.

This env.py configures Alembic to use the researcharr database models
as the source of truth for autogenerated migrations.
"""

from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool

from alembic import context

# Import the Base metadata from researcharr models
from researcharr.storage.models import Base


# Optional: create a pre-migration backup when enabled
def _maybe_backup_before_migrate() -> None:
    try:
        import os

        if os.getenv("RESEARCHARR_BACKUP_BEFORE_MIGRATE", "true").lower() not in (
            "1",
            "true",
            "yes",
            "on",
        ):
            return
        # Determine config and backups directories
        config_root = os.getenv("CONFIG_DIR")
        if not config_root:
            return
        backups_dir = os.path.join(config_root, "backups")
        from researcharr import backups as _bak

        try:
            _bak.create_backup_file(config_root, backups_dir, prefix="pre-migrate-")
        except Exception:
            # Never fail migrations due to backup errors
            pass
    except Exception:
        pass


# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Interpret the config file for Python logging.
# This line sets up loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# add your model's MetaData object here
# for 'autogenerate' support
target_metadata = Base.metadata

# other values from the config, defined by the needs of env.py,
# can be acquired:
# my_important_option = config.get_main_option("my_important_option")
# ... etc.


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.

    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        # Enable compare_type to detect column type changes
        compare_type=True,
        # Enable render_as_batch for SQLite ALTER support
        render_as_batch=True,
    )

    with context.begin_transaction():
        # Best-effort pre-migration backup
        _maybe_backup_before_migrate()
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """
    # If no URL is set in alembic.ini, use a default SQLite path
    # (migrations can be generated without connecting to a real DB)
    configuration = config.get_section(config.config_ini_section, {})
    if not configuration.get("sqlalchemy.url"):
        configuration["sqlalchemy.url"] = "sqlite:///researcharr.db"

    connectable = engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            # Enable compare_type to detect column type changes
            compare_type=True,
            # Enable render_as_batch for SQLite ALTER support
            render_as_batch=True,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
